### ISSUE TITLE
battle and routeSwitch

### ISSUE THREAD

**Issue by bobbyfunks** [ajw120/Undertale#12]
I was thinking something like this for the major battles that come up
  ```<battle>
                  <choice>
                        <option what="kill"> -or "spare"
                            <routeSwitch what="pacifistToNeutral"/> -or "genocideToNeutral"
                        </option>
                    </choice>
                </battle>
```
there's an example in the Snowdin xml, line 831

**Comment by ebeshero** [comment]
@bobbyfunks Sorry for the delayed response here. What I remember from when we revised your project schema is that all shifts in your gameplay mode would be handled with the `<path>` element like this from waterfall.xml:

```xml
   <setting name="UndyneHouse">
            <path route="neutral genocide">
            <sp speaker="Papyrus">
                <conditions killed="Undyne">
                    <box n="1">HEY! READY TO HANG OUT WITH UNDYNE???</box>
                    <box n="2">GREAT!!! ME TOO!!!</box>
                    <box n="3">HOWEVER, SHE'S NOT HERE.</box>
                    <box n="4">NORMALLY SHE RETURNS AT ABOUT THIS TIME</box>
                    <box n="5">SHE'S LATE THOUGH...</box>
                    <box n="6">AND SHE'S NOT ANSWERING HER PHONE</box>
                    <box n="7"> </box>
                </conditions>
            </sp></path>
        </setting>
```
What I understood from our group discussion was that most (all?) map locations have all three path routes ("pacifist" | "neutral" | "genocide") available from the start. But only if all decisions to kill are either avoided or committed does the game determine whether you've completed it in pacifist or genocide mode. So that would mean that a decision *either to kill or spare* would always put a character in neutral mode (as you're indicating here).  When @Bennediction and I discussed this earlier this month, I think we figured out that `<path route="neutral">`,`<path route="neutral genocide">` or `<path route="neutral pacifist">` was a good way to designate these kill or spare decisions in the code. @Bennediction would you like to comment here?

**Comment by cozyycoding** [comment]
Issue resolved in meeting
